version: '3'
services:
  flask-backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    depends_on:
      - flask-backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./react-frontend/build:/usr/share/nginx/html
    depends_on:
      - flask-backend
      - react-frontend
